version: '3.8'

services:
   db:
     container_name: postgres 
     restart: always
     image: postgres:11-alpine
     environment:
       - POSTGRES_PASSWORD=password 
     ports: 
       - "5432:5432"
     volumes:
       - "dbdata:/var/lib/postgresql/data"
   
   redis:
     image: redis:latest
     command: redis-server
     ports:
       - "6379:6379"
   
   sidekiq:
     depends_on:
       - 'db'
       - 'redis'
     build: .
     command: bundle exec sidekiq
     volumes:
       - '.:/app'
     #  - '/app/tmp' # don't mount tmp directory
     environment:
       - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    
   web:
      build: .
    #  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
      ports: 
        - "3000:3000"
      depends_on:
        - db 
        - redis 
      environment:
        - DATABASE_URL=postgres://postgres:password@db:5432/housev
        - REDIS_URL=redis://redis:6379
      volumes:
        - .:/app

volumes:
  dbdata:
