require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/favorite_houses", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FavoriteHouse. As you add validations to FavoriteHouse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FavoriteHouse.create! valid_attributes
      get favorite_houses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      favorite_house = FavoriteHouse.create! valid_attributes
      get favorite_house_url(favorite_house)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_favorite_house_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      favorite_house = FavoriteHouse.create! valid_attributes
      get edit_favorite_house_url(favorite_house)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FavoriteHouse" do
        expect {
          post favorite_houses_url, params: { favorite_house: valid_attributes }
        }.to change(FavoriteHouse, :count).by(1)
      end

      it "redirects to the created favorite_house" do
        post favorite_houses_url, params: { favorite_house: valid_attributes }
        expect(response).to redirect_to(favorite_house_url(FavoriteHouse.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FavoriteHouse" do
        expect {
          post favorite_houses_url, params: { favorite_house: invalid_attributes }
        }.to change(FavoriteHouse, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post favorite_houses_url, params: { favorite_house: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested favorite_house" do
        favorite_house = FavoriteHouse.create! valid_attributes
        patch favorite_house_url(favorite_house), params: { favorite_house: new_attributes }
        favorite_house.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the favorite_house" do
        favorite_house = FavoriteHouse.create! valid_attributes
        patch favorite_house_url(favorite_house), params: { favorite_house: new_attributes }
        favorite_house.reload
        expect(response).to redirect_to(favorite_house_url(favorite_house))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        favorite_house = FavoriteHouse.create! valid_attributes
        patch favorite_house_url(favorite_house), params: { favorite_house: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested favorite_house" do
      favorite_house = FavoriteHouse.create! valid_attributes
      expect {
        delete favorite_house_url(favorite_house)
      }.to change(FavoriteHouse, :count).by(-1)
    end

    it "redirects to the favorite_houses list" do
      favorite_house = FavoriteHouse.create! valid_attributes
      delete favorite_house_url(favorite_house)
      expect(response).to redirect_to(favorite_houses_url)
    end
  end
end
