require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/favorite_lands", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FavoriteLand. As you add validations to FavoriteLand, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FavoriteLand.create! valid_attributes
      get favorite_lands_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      favorite_land = FavoriteLand.create! valid_attributes
      get favorite_land_url(favorite_land)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_favorite_land_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      favorite_land = FavoriteLand.create! valid_attributes
      get edit_favorite_land_url(favorite_land)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FavoriteLand" do
        expect {
          post favorite_lands_url, params: { favorite_land: valid_attributes }
        }.to change(FavoriteLand, :count).by(1)
      end

      it "redirects to the created favorite_land" do
        post favorite_lands_url, params: { favorite_land: valid_attributes }
        expect(response).to redirect_to(favorite_land_url(FavoriteLand.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FavoriteLand" do
        expect {
          post favorite_lands_url, params: { favorite_land: invalid_attributes }
        }.to change(FavoriteLand, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post favorite_lands_url, params: { favorite_land: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested favorite_land" do
        favorite_land = FavoriteLand.create! valid_attributes
        patch favorite_land_url(favorite_land), params: { favorite_land: new_attributes }
        favorite_land.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the favorite_land" do
        favorite_land = FavoriteLand.create! valid_attributes
        patch favorite_land_url(favorite_land), params: { favorite_land: new_attributes }
        favorite_land.reload
        expect(response).to redirect_to(favorite_land_url(favorite_land))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        favorite_land = FavoriteLand.create! valid_attributes
        patch favorite_land_url(favorite_land), params: { favorite_land: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested favorite_land" do
      favorite_land = FavoriteLand.create! valid_attributes
      expect {
        delete favorite_land_url(favorite_land)
      }.to change(FavoriteLand, :count).by(-1)
    end

    it "redirects to the favorite_lands list" do
      favorite_land = FavoriteLand.create! valid_attributes
      delete favorite_land_url(favorite_land)
      expect(response).to redirect_to(favorite_lands_url)
    end
  end
end
