require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/plans_selecteds", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PlansSelected. As you add validations to PlansSelected, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PlansSelected.create! valid_attributes
      get plans_selecteds_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      plans_selected = PlansSelected.create! valid_attributes
      get plans_selected_url(plans_selected)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_plans_selected_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      plans_selected = PlansSelected.create! valid_attributes
      get edit_plans_selected_url(plans_selected)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PlansSelected" do
        expect {
          post plans_selecteds_url, params: { plans_selected: valid_attributes }
        }.to change(PlansSelected, :count).by(1)
      end

      it "redirects to the created plans_selected" do
        post plans_selecteds_url, params: { plans_selected: valid_attributes }
        expect(response).to redirect_to(plans_selected_url(PlansSelected.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PlansSelected" do
        expect {
          post plans_selecteds_url, params: { plans_selected: invalid_attributes }
        }.to change(PlansSelected, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post plans_selecteds_url, params: { plans_selected: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested plans_selected" do
        plans_selected = PlansSelected.create! valid_attributes
        patch plans_selected_url(plans_selected), params: { plans_selected: new_attributes }
        plans_selected.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the plans_selected" do
        plans_selected = PlansSelected.create! valid_attributes
        patch plans_selected_url(plans_selected), params: { plans_selected: new_attributes }
        plans_selected.reload
        expect(response).to redirect_to(plans_selected_url(plans_selected))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        plans_selected = PlansSelected.create! valid_attributes
        patch plans_selected_url(plans_selected), params: { plans_selected: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested plans_selected" do
      plans_selected = PlansSelected.create! valid_attributes
      expect {
        delete plans_selected_url(plans_selected)
      }.to change(PlansSelected, :count).by(-1)
    end

    it "redirects to the plans_selecteds list" do
      plans_selected = PlansSelected.create! valid_attributes
      delete plans_selected_url(plans_selected)
      expect(response).to redirect_to(plans_selecteds_url)
    end
  end
end
