require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/profile_lands", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProfileLand. As you add validations to ProfileLand, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProfileLand.create! valid_attributes
      get profile_lands_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      profile_land = ProfileLand.create! valid_attributes
      get profile_land_url(profile_land)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_profile_land_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      profile_land = ProfileLand.create! valid_attributes
      get edit_profile_land_url(profile_land)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProfileLand" do
        expect {
          post profile_lands_url, params: { profile_land: valid_attributes }
        }.to change(ProfileLand, :count).by(1)
      end

      it "redirects to the created profile_land" do
        post profile_lands_url, params: { profile_land: valid_attributes }
        expect(response).to redirect_to(profile_land_url(ProfileLand.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProfileLand" do
        expect {
          post profile_lands_url, params: { profile_land: invalid_attributes }
        }.to change(ProfileLand, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post profile_lands_url, params: { profile_land: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested profile_land" do
        profile_land = ProfileLand.create! valid_attributes
        patch profile_land_url(profile_land), params: { profile_land: new_attributes }
        profile_land.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the profile_land" do
        profile_land = ProfileLand.create! valid_attributes
        patch profile_land_url(profile_land), params: { profile_land: new_attributes }
        profile_land.reload
        expect(response).to redirect_to(profile_land_url(profile_land))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        profile_land = ProfileLand.create! valid_attributes
        patch profile_land_url(profile_land), params: { profile_land: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested profile_land" do
      profile_land = ProfileLand.create! valid_attributes
      expect {
        delete profile_land_url(profile_land)
      }.to change(ProfileLand, :count).by(-1)
    end

    it "redirects to the profile_lands list" do
      profile_land = ProfileLand.create! valid_attributes
      delete profile_land_url(profile_land)
      expect(response).to redirect_to(profile_lands_url)
    end
  end
end
